spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce_db

server:
  port: 8080

razorpay:
  keyId: ${RAZORPAY_KEY_ID}
  keySecret: ${RAZORPAY_KEY_SECRET}
  webhookSecret: ${RAZORPAY_WEBHOOK_SECRET:dummy_webhook_secret}
