spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce_db

server:
  port: 8080

razorpay:
  keyId: rzp_live_S65RI7ZRfslGLO
  keySecret: kwTRk1NLskR2C244D4hk9NW9
  webhookSecret: PASTE_WEBHOOK_SECRET
